/* ═══════════════════════════════════════════════════
   LEARNSPHERE – Domain Data Structure
   ═══════════════════════════════════════════════════ */

const DOMAIN_DATA = [
  {
    id: "core-it",
    icon: "💻",
    title: "Core IT & Software Domains",
    description: "Foundational technology skills from web development to cybersecurity.",
    subDomains: [
      {
        id: "web-dev",
        title: "Web Development",
        description: "Frontend, Backend & Full Stack web technologies.",
        intro: "Web Development is the process of building websites and web applications. It encompasses everything from simple static pages to complex web-based applications, e-commerce sites, and social networks.",
        importance: "Web development is one of the most in-demand skills globally. Every business needs a web presence, making this a recession-proof career with endless opportunities.",
        skills: ["HTML5 & CSS3", "JavaScript / TypeScript", "React / Angular / Vue", "Node.js / Express", "REST APIs & GraphQL", "Databases (SQL & NoSQL)", "Git & Version Control"],
        path: [
          { level: "Beginner", steps: "Learn HTML, CSS basics → Build static pages → Learn responsive design" },
          { level: "Intermediate", steps: "Learn JavaScript → DOM manipulation → React or Vue → REST APIs" },
          { level: "Advanced", steps: "Full-stack with Node.js → Authentication → Deployment → DevOps basics" }
        ],
        howToLearn: "Start by building simple web pages with HTML and CSS. Then add interactivity with JavaScript. Pick a framework like React, and build projects like a portfolio site, a to-do app, and an e-commerce clone.",
        youtube: ["https://www.youtube.com/embed/UB1O30fR-EE", "https://www.youtube.com/embed/PkZNo7MFNFg"],
        freePlatforms: ["freeCodeCamp.org", "The Odin Project", "MDN Web Docs", "Coursera – HTML/CSS/JS for Web Developers"],
        careers: ["Frontend Developer", "Backend Developer", "Full Stack Developer", "Web Designer", "UI Engineer"],
        tools: ["VS Code", "Chrome DevTools", "GitHub", "Figma", "Postman", "Webpack / Vite"]
      },
      {
        id: "mobile-dev",
        title: "Mobile App Development",
        description: "Build native and cross-platform mobile applications.",
        intro: "Mobile App Development involves creating software applications that run on mobile devices like smartphones and tablets.",
        importance: "With billions of smartphone users worldwide, mobile apps are essential for businesses. The demand for skilled mobile developers continues to grow rapidly.",
        skills: ["React Native / Flutter", "Swift (iOS)", "Kotlin (Android)", "UI/UX for Mobile", "APIs & State Management", "App Store Deployment"],
        path: [
          { level: "Beginner", steps: "Learn programming basics → Choose a platform → Build simple apps" },
          { level: "Intermediate", steps: "State management → API integration → Local storage → Navigation" },
          { level: "Advanced", steps: "Performance optimization → CI/CD → Analytics → Monetization" }
        ],
        howToLearn: "Pick Flutter or React Native to build cross-platform apps quickly. Start with simple projects like a calculator or weather app, then progress to more complex applications.",
        youtube: ["https://www.youtube.com/embed/VPvVD8t02U8", "https://www.youtube.com/embed/0-S5a0eXPoc"],
        freePlatforms: ["Flutter.dev official tutorials", "React Native docs", "Udacity Mobile Dev Nanodegree (free tier)", "Coursera – Meta React Native"],
        careers: ["iOS Developer", "Android Developer", "React Native Developer", "Flutter Developer", "Mobile Architect"],
        tools: ["Android Studio", "Xcode", "VS Code", "Firebase", "Expo"]
      },
      {
        id: "data-science",
        title: "Data Science",
        description: "Extract insights from data using statistics and programming.",
        intro: "Data Science combines statistics, programming, and domain expertise to extract meaningful insights and knowledge from structured and unstructured data.",
        importance: "Data is the new oil. Organizations rely on data scientists to make data-driven decisions, predict trends, and gain competitive advantages.",
        skills: ["Python / R", "Pandas & NumPy", "Data Visualization", "Statistical Analysis", "SQL", "Jupyter Notebooks"],
        path: [
          { level: "Beginner", steps: "Learn Python → Statistics basics → Pandas for data manipulation" },
          { level: "Intermediate", steps: "Data visualization → SQL → Exploratory Data Analysis → Feature engineering" },
          { level: "Advanced", steps: "Machine Learning integration → Big Data tools → Real-world projects" }
        ],
        howToLearn: "Start with Python and basic statistics. Use Kaggle datasets to practice. Learn to tell stories with data using matplotlib and seaborn.",
        youtube: ["https://www.youtube.com/embed/ua-CiDNNj30", "https://www.youtube.com/embed/LHBE6Q9XlzI"],
        freePlatforms: ["Kaggle Learn", "Coursera – IBM Data Science", "freeCodeCamp Data Analysis with Python", "DataCamp (free tier)"],
        careers: ["Data Scientist", "Data Analyst", "Business Analyst", "Research Scientist", "Quantitative Analyst"],
        tools: ["Jupyter Notebook", "Python", "Tableau", "Power BI", "Excel", "SQL"]
      },
      {
        id: "ai",
        title: "Artificial Intelligence",
        description: "Build intelligent systems that simulate human cognition.",
        intro: "Artificial Intelligence is the simulation of human intelligence by machines, enabling them to learn, reason, and make decisions autonomously.",
        importance: "AI is transforming every industry from healthcare to finance. It's one of the most impactful technologies of the 21st century with massive career potential.",
        skills: ["Python", "Neural Networks", "NLP", "Computer Vision", "TensorFlow / PyTorch", "Reinforcement Learning"],
        path: [
          { level: "Beginner", steps: "Learn Python → Math foundations (linear algebra, calculus) → ML basics" },
          { level: "Intermediate", steps: "Deep Learning → CNNs & RNNs → NLP fundamentals → Model training" },
          { level: "Advanced", steps: "GANs → Transformers → MLOps → Research papers → Production AI" }
        ],
        howToLearn: "Master Python first, then study math fundamentals. Take Andrew Ng's courses. Build projects like image classifiers and chatbots.",
        youtube: ["https://www.youtube.com/embed/JMUxmLyrhSk", "https://www.youtube.com/embed/aircAruvnKk"],
        freePlatforms: ["Coursera – AI For Everyone (Andrew Ng)", "fast.ai", "Google AI Education", "MIT OpenCourseWare"],
        careers: ["AI Engineer", "ML Engineer", "AI Research Scientist", "NLP Engineer", "Computer Vision Engineer"],
        tools: ["TensorFlow", "PyTorch", "Hugging Face", "OpenCV", "Google Colab"]
      },
      {
        id: "ml",
        title: "Machine Learning",
        description: "Teach computers to learn patterns from data.",
        intro: "Machine Learning is a subset of AI that enables systems to learn and improve from experience without being explicitly programmed.",
        importance: "ML powers recommendation systems, fraud detection, autonomous vehicles, and countless other applications transforming business and society.",
        skills: ["Supervised Learning", "Unsupervised Learning", "Scikit-learn", "Feature Engineering", "Model Evaluation", "Ensemble Methods"],
        path: [
          { level: "Beginner", steps: "Python + Math → Linear/Logistic Regression → Decision Trees" },
          { level: "Intermediate", steps: "SVMs → Random Forests → Clustering → Cross-validation" },
          { level: "Advanced", steps: "XGBoost → Neural Networks → AutoML → Model deployment" }
        ],
        howToLearn: "Start with scikit-learn and simple datasets. Understand the math behind algorithms. Participate in Kaggle competitions to sharpen skills.",
        youtube: ["https://www.youtube.com/embed/i_LwzRVP7bg", "https://www.youtube.com/embed/Gv9_4yMHFhI"],
        freePlatforms: ["Coursera – Machine Learning (Andrew Ng)", "Kaggle", "Google ML Crash Course", "scikit-learn docs"],
        careers: ["ML Engineer", "Data Scientist", "ML Researcher", "AI Product Manager"],
        tools: ["scikit-learn", "TensorFlow", "Jupyter", "Weights & Biases", "MLflow"]
      },
      {
        id: "cloud",
        title: "Cloud Computing",
        description: "Deploy and manage applications on cloud infrastructure.",
        intro: "Cloud Computing delivers computing services over the internet including servers, storage, databases, networking, and AI services.",
        importance: "Nearly every organization is migrating to the cloud. Cloud skills are among the highest-paid and most demanded in IT.",
        skills: ["AWS / Azure / GCP", "Virtual Machines", "Containers", "Serverless", "Cloud Security", "IaC (Terraform)"],
        path: [
          { level: "Beginner", steps: "Cloud concepts → Choose AWS/Azure/GCP → Basic services (EC2, S3)" },
          { level: "Intermediate", steps: "Networking → Databases → IAM → Load balancing → Auto-scaling" },
          { level: "Advanced", steps: "Kubernetes → Serverless → Multi-cloud → Cost optimization → Certifications" }
        ],
        howToLearn: "Sign up for a free tier account on AWS or Azure. Follow hands-on labs. Work toward a foundational certification like AWS Cloud Practitioner.",
        youtube: ["https://www.youtube.com/embed/3hLmDS179YE", "https://www.youtube.com/embed/r4YIdn2eTm4"],
        freePlatforms: ["AWS Free Tier + Training", "Azure Learn", "Google Cloud Skills Boost", "A Cloud Guru (free tier)"],
        careers: ["Cloud Engineer", "Cloud Architect", "SRE", "Cloud Security Engineer", "DevOps Engineer"],
        tools: ["AWS Console", "Azure Portal", "Terraform", "Docker", "Kubernetes"]
      },
      {
        id: "cybersecurity",
        title: "Cyber Security",
        description: "Protect systems, networks, and data from digital attacks.",
        intro: "Cyber Security involves protecting computer systems, networks, and data from unauthorized access, attacks, and damage.",
        importance: "With increasing cyber threats, organizations desperately need security professionals. It's one of the fastest-growing and highest-paying fields in IT.",
        skills: ["Network Security", "Ethical Hacking", "Cryptography", "SIEM", "Vulnerability Assessment", "Incident Response"],
        path: [
          { level: "Beginner", steps: "Networking fundamentals → Linux basics → Security concepts" },
          { level: "Intermediate", steps: "Penetration testing → OWASP Top 10 → Firewalls & IDS" },
          { level: "Advanced", steps: "Malware analysis → Forensics → Red/Blue teaming → Compliance" }
        ],
        howToLearn: "Start with CompTIA Security+ study material. Practice on TryHackMe and HackTheBox. Learn Linux thoroughly.",
        youtube: ["https://www.youtube.com/embed/U_P23SqJaDc", "https://www.youtube.com/embed/hXSFdwIOfnE"],
        freePlatforms: ["TryHackMe", "HackTheBox", "Cybrary (free tier)", "OWASP resources"],
        careers: ["Security Analyst", "Penetration Tester", "SOC Analyst", "Security Architect", "CISO"],
        tools: ["Wireshark", "Metasploit", "Burp Suite", "Nmap", "Kali Linux"]
      },
      {
        id: "devops",
        title: "DevOps Engineering",
        description: "Bridge development and operations with automation.",
        intro: "DevOps is a culture and set of practices that brings together software development and IT operations to shorten the development lifecycle.",
        importance: "DevOps practices are now standard in the industry. Companies that adopt DevOps ship faster, more reliably, with fewer failures.",
        skills: ["CI/CD Pipelines", "Docker & Kubernetes", "Infrastructure as Code", "Monitoring", "Linux Administration", "Scripting (Bash/Python)"],
        path: [
          { level: "Beginner", steps: "Linux → Git → Basic scripting → CI/CD concepts" },
          { level: "Intermediate", steps: "Docker → Jenkins/GitHub Actions → Terraform → Monitoring" },
          { level: "Advanced", steps: "Kubernetes → Service mesh → GitOps → SRE practices" }
        ],
        howToLearn: "Learn Linux and shell scripting first. Then containerize apps with Docker. Set up CI/CD pipelines for your own projects.",
        youtube: ["https://www.youtube.com/embed/j5Zsa_eOXeY", "https://www.youtube.com/embed/0yWAtQ6wYNM"],
        freePlatforms: ["KodeKloud (free labs)", "Linux Academy", "Docker docs", "Kubernetes.io tutorials"],
        careers: ["DevOps Engineer", "SRE", "Platform Engineer", "Release Manager", "Cloud Engineer"],
        tools: ["Docker", "Kubernetes", "Jenkins", "Terraform", "Ansible", "Prometheus"]
      },
      {
        id: "testing",
        title: "Software Testing",
        description: "Ensure software quality through systematic testing.",
        intro: "Software Testing is the process of evaluating software to detect differences between expected and actual outcomes, ensuring quality and reliability.",
        importance: "Quality assurance is critical in software development. No product ships without testing, making it a stable and essential career path.",
        skills: ["Manual Testing", "Automation (Selenium)", "API Testing", "Performance Testing", "Test Planning", "Agile QA"],
        path: [
          { level: "Beginner", steps: "Testing fundamentals → Test case writing → Bug reporting" },
          { level: "Intermediate", steps: "Selenium → API testing (Postman) → CI integration" },
          { level: "Advanced", steps: "Performance testing → Security testing → Test architecture" }
        ],
        howToLearn: "Start with manual testing concepts. Learn to write test cases. Then move to Selenium WebDriver for automation.",
        youtube: ["https://www.youtube.com/embed/u5senBJUkPc", "https://www.youtube.com/embed/oqvdq84cBME"],
        freePlatforms: ["Guru99 Testing Tutorials", "Test Automation University", "Selenium docs", "Coursera – Software Testing"],
        careers: ["QA Engineer", "Test Automation Engineer", "SDET", "Performance Tester", "QA Lead"],
        tools: ["Selenium", "Postman", "JMeter", "Cypress", "Jest"]
      },
      {
        id: "uiux",
        title: "UI/UX Design",
        description: "Design intuitive and beautiful user experiences.",
        intro: "UI/UX Design focuses on creating products that provide meaningful and relevant experiences to users, encompassing the entire process of design.",
        importance: "Great design differentiates successful products. Companies invest heavily in UX to improve user satisfaction, retention, and conversion.",
        skills: ["User Research", "Wireframing", "Prototyping", "Visual Design", "Usability Testing", "Design Systems"],
        path: [
          { level: "Beginner", steps: "Design principles → Figma basics → Wireframing" },
          { level: "Intermediate", steps: "User research → Prototyping → Design systems → Accessibility" },
          { level: "Advanced", steps: "Motion design → Advanced interactions → Design leadership" }
        ],
        howToLearn: "Learn design fundamentals and start with Figma. Redesign existing apps as practice. Study great designs on Dribbble and Behance.",
        youtube: ["https://www.youtube.com/embed/c9Wg6Cb_YlU", "https://www.youtube.com/embed/68w2VwalD5w"],
        freePlatforms: ["Google UX Design Certificate (Coursera)", "Figma tutorials", "Interaction Design Foundation", "Laws of UX"],
        careers: ["UI Designer", "UX Designer", "Product Designer", "UX Researcher", "Design Lead"],
        tools: ["Figma", "Adobe XD", "Sketch", "Miro", "InVision"]
      }
    ]
  },
  {
    id: "trending-tech",
    icon: "🚀",
    title: "Advanced / Trending Tech Domains",
    description: "Cutting-edge technologies shaping the future of innovation.",
    subDomains: [
      { id: "blockchain", title: "Blockchain & Web3", description: "Decentralized applications and smart contracts.",
        intro: "Blockchain is a distributed ledger technology that enables secure, transparent, and tamper-proof transactions without intermediaries.",
        importance: "From cryptocurrency to supply chain, blockchain is revolutionizing industries with decentralized solutions.",
        skills: ["Solidity", "Smart Contracts", "Ethereum", "DeFi", "NFTs", "Web3.js"],
        path: [{ level: "Beginner", steps: "Blockchain concepts → Crypto basics → First smart contract" }, { level: "Intermediate", steps: "Solidity → DApp development → Testing → Security" }, { level: "Advanced", steps: "DeFi protocols → Layer 2 → Cross-chain → Auditing" }],
        howToLearn: "Understand blockchain fundamentals, then learn Solidity. Deploy contracts on testnets. Build a DApp.",
        youtube: ["https://www.youtube.com/embed/gyMwXuJrbJQ", "https://www.youtube.com/embed/M576WGiDBdQ"],
        freePlatforms: ["CryptoZombies", "Ethereum.org tutorials", "Buildspace", "Alchemy University"],
        careers: ["Blockchain Developer", "Smart Contract Engineer", "Web3 Developer", "DeFi Analyst"],
        tools: ["Remix IDE", "Hardhat", "MetaMask", "Etherscan", "IPFS"] },
      { id: "iot", title: "Internet of Things (IoT)", description: "Connect physical devices to the digital world.",
        intro: "IoT connects everyday physical objects to the internet, enabling them to collect and exchange data.",
        importance: "IoT is transforming healthcare, manufacturing, agriculture, and smart cities with billions of connected devices.",
        skills: ["Sensors & Actuators", "Arduino / Raspberry Pi", "MQTT Protocol", "Edge Computing", "Embedded C", "Cloud IoT"],
        path: [{ level: "Beginner", steps: "Electronics basics → Arduino projects → Sensor data" }, { level: "Intermediate", steps: "Raspberry Pi → MQTT → Cloud dashboards → Data analytics" }, { level: "Advanced", steps: "Edge AI → Industrial IoT → Security → System design" }],
        howToLearn: "Start with Arduino kits. Build simple sensor projects. Progress to Raspberry Pi and cloud-connected solutions.",
        youtube: ["https://www.youtube.com/embed/LlhmzVL5bm8", "https://www.youtube.com/embed/6mBO2vqLv38"],
        freePlatforms: ["Arduino.cc tutorials", "Coursera – IoT Specialization", "AWS IoT Core docs", "Hackster.io"],
        careers: ["IoT Developer", "Embedded Engineer", "IoT Architect", "Hardware Engineer"],
        tools: ["Arduino IDE", "Raspberry Pi", "MQTT", "AWS IoT", "Node-RED"] },
      { id: "ar-vr", title: "AR / VR Development", description: "Build immersive augmented and virtual reality experiences.",
        intro: "AR/VR creates immersive digital experiences by overlaying digital content on the real world (AR) or creating entirely virtual environments (VR).",
        importance: "The metaverse and spatial computing are driving massive investment in AR/VR across gaming, education, healthcare, and enterprise.",
        skills: ["Unity / Unreal Engine", "3D Modeling", "C# / C++", "Spatial Computing", "WebXR", "Interaction Design"],
        path: [{ level: "Beginner", steps: "Unity basics → 3D concepts → Simple VR scene" }, { level: "Intermediate", steps: "Interaction systems → Physics → AR Foundation → UI in 3D" }, { level: "Advanced", steps: "Multiplayer VR → Performance → Haptics → Enterprise solutions" }],
        howToLearn: "Start with Unity and C#. Follow Unity's XR tutorials. Build a simple VR experience.",
        youtube: ["https://www.youtube.com/embed/gY1Mn7OH6R8", "https://www.youtube.com/embed/WzfDo2Wpxks"],
        freePlatforms: ["Unity Learn", "Coursera – VR Specialization", "Google ARCore docs", "A-Frame (WebVR)"],
        careers: ["AR/VR Developer", "3D Developer", "Unity Developer", "XR Engineer"],
        tools: ["Unity", "Unreal Engine", "Blender", "Oculus SDK", "ARCore / ARKit"] },
      { id: "quantum", title: "Quantum Computing", description: "Explore computing beyond classical limitations.",
        intro: "Quantum Computing uses quantum-mechanical phenomena like superposition and entanglement to process information exponentially faster for certain problems.",
        importance: "Quantum computing will revolutionize cryptography, drug discovery, optimization, and AI, making it a frontier skill.",
        skills: ["Quantum Mechanics Basics", "Qubits & Gates", "Qiskit / Cirq", "Quantum Algorithms", "Linear Algebra"],
        path: [{ level: "Beginner", steps: "Linear algebra review → Quantum concepts → Qiskit intro" }, { level: "Intermediate", steps: "Quantum gates → Grover's algorithm → Shor's algorithm" }, { level: "Advanced", steps: "Quantum ML → Error correction → Research applications" }],
        howToLearn: "Strengthen linear algebra skills. Take IBM's Qiskit courses. Experiment on IBM Quantum Experience.",
        youtube: ["https://www.youtube.com/embed/OWJCfOvochA", "https://www.youtube.com/embed/F_Riqjdh2oM"],
        freePlatforms: ["IBM Quantum Learning", "Qiskit Textbook", "Microsoft Quantum docs", "Coursera – Quantum Computing"],
        careers: ["Quantum Software Engineer", "Quantum Researcher", "Quantum Algorithm Developer"],
        tools: ["Qiskit", "Cirq", "IBM Quantum Experience", "Amazon Braket"] }
    ]
  },
  {
    id: "data-analytics",
    icon: "📊",
    title: "Data & Analytics Domains",
    description: "Transform raw data into actionable business intelligence.",
    subDomains: [
      { id: "big-data", title: "Big Data Engineering", description: "Process and analyze massive datasets at scale.",
        intro: "Big Data Engineering focuses on building systems and infrastructure to collect, store, and process massive volumes of data.",
        importance: "Every major company needs big data infrastructure. It's the backbone of data-driven decision making.",
        skills: ["Hadoop / Spark", "Kafka", "Data Pipelines", "ETL", "Data Warehousing", "SQL & NoSQL"],
        path: [{ level: "Beginner", steps: "SQL mastery → Python → Data pipeline concepts" }, { level: "Intermediate", steps: "Apache Spark → Kafka → Airflow → Cloud data services" }, { level: "Advanced", steps: "Real-time streaming → Data lakehouse → Optimization → Governance" }],
        howToLearn: "Master SQL first. Learn Python for data processing. Then explore Spark and build ETL pipelines.",
        youtube: ["https://www.youtube.com/embed/yDGUjkzWXOE", "https://www.youtube.com/embed/KerNf0NANMo"],
        freePlatforms: ["Coursera – Big Data Specialization", "Databricks Academy", "Apache Spark docs", "Kaggle"],
        careers: ["Data Engineer", "Big Data Engineer", "ETL Developer", "Data Architect"],
        tools: ["Apache Spark", "Kafka", "Airflow", "Snowflake", "Databricks"] },
      { id: "bi", title: "Business Intelligence", description: "Create dashboards and reports for data-driven decisions.",
        intro: "Business Intelligence transforms raw data into meaningful insights through dashboards, reports, and visualizations.",
        importance: "BI professionals help organizations make informed decisions. Every department from marketing to finance relies on BI.",
        skills: ["Power BI", "Tableau", "SQL", "Data Modeling", "DAX", "ETL Basics"],
        path: [{ level: "Beginner", steps: "Excel analytics → SQL → Basic Power BI/Tableau" }, { level: "Intermediate", steps: "Advanced DAX → Data modeling → Dashboard design" }, { level: "Advanced", steps: "Enterprise BI → Governance → Performance tuning → Self-service BI" }],
        howToLearn: "Start with Excel and SQL. Pick Power BI or Tableau and build dashboards using public datasets.",
        youtube: ["https://www.youtube.com/embed/AGrl-H87pRU", "https://www.youtube.com/embed/i2tms184QCM"],
        freePlatforms: ["Microsoft Learn – Power BI", "Tableau Public", "Coursera – Google Data Analytics", "freeCodeCamp"],
        careers: ["BI Analyst", "BI Developer", "Data Analyst", "Analytics Manager"],
        tools: ["Power BI", "Tableau", "Looker", "Excel", "SQL Server"] },
      { id: "data-eng", title: "Data Engineering", description: "Build robust data pipelines and infrastructure.",
        intro: "Data Engineering is about designing and building systems for collecting, storing, and analyzing data at scale.",
        importance: "Without data engineers, data scientists can't do their work. It's a critical role bridging raw data and analytics.",
        skills: ["Python", "SQL", "Apache Airflow", "dbt", "Cloud Data Services", "Data Modeling"],
        path: [{ level: "Beginner", steps: "Python → SQL → Data formats (JSON, Parquet)" }, { level: "Intermediate", steps: "ETL tools → Airflow → dbt → Cloud warehouses" }, { level: "Advanced", steps: "Real-time pipelines → Data mesh → Cost optimization" }],
        howToLearn: "Master SQL and Python. Build ETL pipelines using Airflow. Practice with cloud data services.",
        youtube: ["https://www.youtube.com/embed/qWru-b6m030", "https://www.youtube.com/embed/7mLKPYPhP5I"],
        freePlatforms: ["DataTalks.club DE Zoomcamp", "Coursera – Google Data Engineering", "dbt Learn", "Apache Airflow docs"],
        careers: ["Data Engineer", "Analytics Engineer", "Data Platform Engineer", "ML Engineer"],
        tools: ["Airflow", "dbt", "Snowflake", "BigQuery", "Fivetran"] }
    ]
  },
  {
    id: "networking",
    icon: "🌐",
    title: "Networking & Infrastructure",
    description: "Design and maintain the backbone of digital communication.",
    subDomains: [
      { id: "network-admin", title: "Network Administration", description: "Manage and maintain computer networks.",
        intro: "Network Administration involves managing, maintaining, and troubleshooting computer networks to ensure reliable connectivity.",
        importance: "Every organization depends on stable networks. Network admins are essential for daily business operations.",
        skills: ["TCP/IP", "DNS & DHCP", "Routing & Switching", "Firewalls", "VPNs", "Network Monitoring"],
        path: [{ level: "Beginner", steps: "Networking fundamentals → OSI model → IP addressing" }, { level: "Intermediate", steps: "Cisco/Juniper config → VLANs → Routing protocols" }, { level: "Advanced", steps: "SD-WAN → Network automation → Enterprise design" }],
        howToLearn: "Study for CompTIA Network+ or CCNA. Use Packet Tracer for labs. Build a home lab.",
        youtube: ["https://www.youtube.com/embed/qiQR5rTSshw", "https://www.youtube.com/embed/IPvYjXCsTg8"],
        freePlatforms: ["Cisco Networking Academy", "Professor Messer", "Coursera – Google IT Support", "GNS3 Academy"],
        careers: ["Network Administrator", "Network Engineer", "Systems Administrator", "IT Support Specialist"],
        tools: ["Cisco Packet Tracer", "Wireshark", "PuTTY", "GNS3", "Nagios"] },
      { id: "sys-admin", title: "System Administration", description: "Manage servers and IT infrastructure.",
        intro: "System Administration involves managing and maintaining servers, operating systems, and IT infrastructure.",
        importance: "Sys admins keep the digital world running. Every company with IT infrastructure needs skilled system administrators.",
        skills: ["Linux/Windows Server", "Active Directory", "Shell Scripting", "Backup & Recovery", "Virtualization", "Monitoring"],
        path: [{ level: "Beginner", steps: "Linux basics → Command line → User management" }, { level: "Intermediate", steps: "Server setup → Automation → Monitoring → Virtualization" }, { level: "Advanced", steps: "High availability → Disaster recovery → Infrastructure as Code" }],
        howToLearn: "Install Linux on a VM. Learn command line. Set up services like web servers and databases.",
        youtube: ["https://www.youtube.com/embed/ROjZy1WbCIA", "https://www.youtube.com/embed/wBp0Rb-ZJak"],
        freePlatforms: ["Linux Journey", "Coursera – Google IT Automation", "Red Hat Academy", "DigitalOcean tutorials"],
        careers: ["System Administrator", "Linux Administrator", "IT Manager", "Infrastructure Engineer"],
        tools: ["Linux", "Windows Server", "VMware", "Ansible", "Zabbix"] }
    ]
  },
  {
    id: "software-eng",
    icon: "⚙️",
    title: "Software Engineering Specializations",
    description: "Advanced software development practices and architectures.",
    subDomains: [
      { id: "backend-eng", title: "Backend Engineering", description: "Build scalable server-side applications.",
        intro: "Backend Engineering focuses on server-side logic, databases, APIs, and the architecture that powers applications.",
        importance: "Backend engineers build the core logic that makes applications work. It's a high-demand, high-paying specialization.",
        skills: ["Node.js / Python / Java", "REST & GraphQL APIs", "Databases", "Authentication", "Caching", "Microservices"],
        path: [{ level: "Beginner", steps: "Pick a language → Build REST APIs → Database basics" }, { level: "Intermediate", steps: "Authentication → Caching → Message queues → Testing" }, { level: "Advanced", steps: "Microservices → System design → Performance → Distributed systems" }],
        howToLearn: "Choose Node.js or Python. Build APIs connected to databases. Learn about authentication and caching.",
        youtube: ["https://www.youtube.com/embed/f2EqECiTBL8", "https://www.youtube.com/embed/pKd0Rpw7O48"],
        freePlatforms: ["freeCodeCamp Backend", "The Odin Project", "Coursera – Meta Backend Developer", "MDN Server-side"],
        careers: ["Backend Developer", "API Developer", "Software Engineer", "Platform Engineer"],
        tools: ["Node.js", "Express", "PostgreSQL", "Redis", "Docker"] },
      { id: "dsa", title: "Data Structures & Algorithms", description: "Master problem-solving for technical interviews.",
        intro: "DSA is the study of organizing data efficiently and designing algorithms to solve computational problems optimally.",
        importance: "DSA is the foundation of computer science and the key to cracking technical interviews at top tech companies.",
        skills: ["Arrays & Strings", "Trees & Graphs", "Dynamic Programming", "Sorting & Searching", "Recursion", "Big-O Notation"],
        path: [{ level: "Beginner", steps: "Big-O → Arrays → Linked Lists → Stacks & Queues" }, { level: "Intermediate", steps: "Trees → Graphs → Hashing → Sorting algorithms" }, { level: "Advanced", steps: "Dynamic Programming → Greedy → Advanced graphs → Contest problems" }],
        howToLearn: "Pick a language (Python/Java/C++). Solve problems daily on LeetCode. Start with easy, progress to hard.",
        youtube: ["https://www.youtube.com/embed/8hly31xKli0", "https://www.youtube.com/embed/pkYVOmU3MgA"],
        freePlatforms: ["LeetCode", "HackerRank", "NeetCode.io", "GeeksforGeeks"],
        careers: ["Software Engineer", "SDE (at FAANG)", "Competitive Programmer", "Algorithm Engineer"],
        tools: ["LeetCode", "VS Code", "Visualgo", "Python/Java/C++"] },
      { id: "system-design", title: "System Design", description: "Architect large-scale distributed systems.",
        intro: "System Design is the process of defining the architecture, components, and data flow of large-scale software systems.",
        importance: "Required for senior engineering roles and essential for building reliable, scalable applications.",
        skills: ["Load Balancing", "Caching Strategies", "Database Sharding", "Message Queues", "CDN", "API Gateway"],
        path: [{ level: "Beginner", steps: "Web architecture → Client-server → Databases → Caching" }, { level: "Intermediate", steps: "Load balancers → Replication → Sharding → Message queues" }, { level: "Advanced", steps: "Distributed consensus → CAP theorem → Real-world systems" }],
        howToLearn: "Study real-world architectures (Netflix, Twitter). Practice designing systems. Read 'Designing Data-Intensive Applications'.",
        youtube: ["https://www.youtube.com/embed/UzLMhqg3_Wc", "https://www.youtube.com/embed/xpDnVSmNFX0"],
        freePlatforms: ["System Design Primer (GitHub)", "ByteByteGo", "Educative.io (free previews)", "Gaurav Sen YouTube"],
        careers: ["Senior Software Engineer", "Staff Engineer", "Solutions Architect", "CTO"],
        tools: ["Draw.io", "Excalidraw", "AWS Architecture Center", "Lucidchart"] }
    ]
  },
  {
    id: "non-it-tech",
    icon: "🔬",
    title: "Non-IT but Tech-Related Domains",
    description: "Interdisciplinary fields where technology meets other industries.",
    subDomains: [
      { id: "biotech", title: "Biotechnology", description: "Apply technology to biological systems.",
        intro: "Biotechnology uses biological systems, organisms, or derivatives to develop products and technologies for healthcare, agriculture, and environment.",
        importance: "Biotech is driving breakthroughs in medicine, agriculture, and environmental science with increasing tech integration.",
        skills: ["Bioinformatics", "Genomics", "Lab Techniques", "Python for Bio", "Data Analysis", "ML for Drug Discovery"],
        path: [{ level: "Beginner", steps: "Biology fundamentals → Bioinformatics intro → Python basics" }, { level: "Intermediate", steps: "Genomic analysis → Biopython → Data visualization" }, { level: "Advanced", steps: "ML for drug discovery → Protein folding → Research" }],
        howToLearn: "Start with biology fundamentals and Python. Learn bioinformatics tools. Practice with public genomic datasets.",
        youtube: ["https://www.youtube.com/embed/QWOdrY1GZIA", "https://www.youtube.com/embed/7Hk9jct2ozY"],
        freePlatforms: ["Coursera – Bioinformatics", "Rosalind.info", "Khan Academy Biology", "NCBI resources"],
        careers: ["Bioinformatics Analyst", "Computational Biologist", "Biotech Researcher", "Data Scientist (Pharma)"],
        tools: ["Python", "R", "BLAST", "Biopython", "Galaxy"] },
      { id: "edtech", title: "EdTech", description: "Technology solutions for education.",
        intro: "Educational Technology combines technology and learning science to create innovative tools and platforms for education.",
        importance: "EdTech is a rapidly growing sector, especially post-pandemic, transforming how people learn worldwide.",
        skills: ["LMS Development", "Content Design", "Gamification", "Analytics", "Accessibility", "Video Production"],
        path: [{ level: "Beginner", steps: "Web development basics → LMS platforms → Content creation" }, { level: "Intermediate", steps: "Interactive content → Analytics → Gamification → APIs" }, { level: "Advanced", steps: "AI tutoring → Adaptive learning → Platform architecture" }],
        howToLearn: "Learn web development first. Explore LMS platforms like Moodle. Build educational tools as projects.",
        youtube: ["https://www.youtube.com/embed/MCi6AZMkxcU", "https://www.youtube.com/embed/dqBhdYijSGs"],
        freePlatforms: ["Coursera – Learning Design", "Google for Education", "Moodle docs", "EdX"],
        careers: ["EdTech Developer", "Instructional Designer", "Learning Engineer", "EdTech Product Manager"],
        tools: ["Moodle", "Canvas", "Articulate", "H5P", "Google Classroom"] }
    ]
  },
  {
    id: "biz-tech",
    icon: "💼",
    title: "Business + Tech Domains",
    description: "Where technology strategy meets business outcomes.",
    subDomains: [
      { id: "product-mgmt", title: "Product Management", description: "Lead product strategy and development lifecycle.",
        intro: "Product Management involves guiding the success of a product by defining its vision, strategy, and roadmap.",
        importance: "Product managers are the CEO of the product. They bridge business, technology, and user experience.",
        skills: ["Product Strategy", "User Research", "Agile/Scrum", "Data Analysis", "Roadmapping", "Stakeholder Management"],
        path: [{ level: "Beginner", steps: "PM fundamentals → User research → Agile basics" }, { level: "Intermediate", steps: "Roadmapping → Metrics (KPIs) → A/B testing → PRDs" }, { level: "Advanced", steps: "Product-led growth → Platform strategy → Team leadership" }],
        howToLearn: "Read 'Inspired' by Marty Cagan. Take a PM course. Build side projects to practice product thinking.",
        youtube: ["https://www.youtube.com/embed/502ILHjX9EE", "https://www.youtube.com/embed/tZkBkTON_Xg"],
        freePlatforms: ["Product School (free resources)", "Coursera – Google PM Certificate", "Mind the Product", "Lenny's Newsletter"],
        careers: ["Product Manager", "Associate PM", "Senior PM", "VP of Product", "CPO"],
        tools: ["Jira", "Notion", "Miro", "Amplitude", "Figma"] },
      { id: "digital-marketing", title: "Digital Marketing", description: "Drive growth through online marketing channels.",
        intro: "Digital Marketing is the promotion of brands and products through digital channels like search engines, social media, email, and websites.",
        importance: "Every business needs digital marketing. It's a versatile skill combining creativity with data-driven decision making.",
        skills: ["SEO", "Google Ads", "Social Media Marketing", "Content Marketing", "Email Marketing", "Analytics"],
        path: [{ level: "Beginner", steps: "Marketing fundamentals → SEO basics → Social media" }, { level: "Intermediate", steps: "Google Ads → Content strategy → Email automation → Analytics" }, { level: "Advanced", steps: "Growth hacking → Marketing automation → Attribution modeling" }],
        howToLearn: "Start with Google Digital Garage. Run campaigns for personal projects. Learn Google Analytics.",
        youtube: ["https://www.youtube.com/embed/bixR-KIJKYM", "https://www.youtube.com/embed/nU-IIXBWlS4"],
        freePlatforms: ["Google Digital Garage", "HubSpot Academy", "Coursera – Google Digital Marketing", "Moz SEO Guide"],
        careers: ["Digital Marketer", "SEO Specialist", "Content Marketer", "Growth Manager", "Marketing Analyst"],
        tools: ["Google Analytics", "Google Ads", "SEMrush", "Mailchimp", "Canva"] },
      { id: "project-mgmt", title: "Project Management", description: "Plan, execute, and deliver successful projects.",
        intro: "Project Management is the discipline of planning, executing, and completing projects within scope, time, and budget constraints.",
        importance: "Every industry needs project managers. It's a universal skill that opens doors across all sectors.",
        skills: ["Agile & Scrum", "Waterfall", "Risk Management", "Budgeting", "Stakeholder Communication", "PMP Framework"],
        path: [{ level: "Beginner", steps: "PM fundamentals → Agile basics → Tools (Jira, Trello)" }, { level: "Intermediate", steps: "Scrum Master → Risk management → Budgeting → Reporting" }, { level: "Advanced", steps: "Program management → Portfolio management → PMP certification" }],
        howToLearn: "Study the PMBOK Guide or take Google's PM certificate. Practice managing real or personal projects.",
        youtube: ["https://www.youtube.com/embed/uWPIsaYpY7U", "https://www.youtube.com/embed/rBSCvljYQ3s"],
        freePlatforms: ["Coursera – Google Project Management", "Scrum.org resources", "PMI free resources", "Atlassian Agile Coach"],
        careers: ["Project Manager", "Scrum Master", "Program Manager", "Delivery Manager", "PMO Director"],
        tools: ["Jira", "Trello", "Asana", "MS Project", "Confluence"] }
    ]
  },
  {
    id: "creative",
    icon: "🎨",
    title: "Creative & Design Domains",
    description: "Blend creativity with technology to build stunning digital experiences.",
    subDomains: [
      { id: "graphic-design", title: "Graphic Design", description: "Create visual content for brands and media.",
        intro: "Graphic Design is the art of visual communication through the use of typography, photography, iconography, and illustration.",
        importance: "Visual content drives engagement. Every brand needs compelling design for marketing, products, and communication.",
        skills: ["Typography", "Color Theory", "Adobe Photoshop", "Adobe Illustrator", "Layout Design", "Brand Identity"],
        path: [{ level: "Beginner", steps: "Design principles → Color theory → Canva/Figma basics" }, { level: "Intermediate", steps: "Adobe Suite → Brand design → Print & digital" }, { level: "Advanced", steps: "Motion graphics → 3D design → Art direction" }],
        howToLearn: "Learn design fundamentals. Start with Canva for quick projects, then learn Adobe tools. Build a portfolio.",
        youtube: ["https://www.youtube.com/embed/YqQx75OPRa0", "https://www.youtube.com/embed/sByzHoiYFX0"],
        freePlatforms: ["Canva Design School", "Coursera – CalArts Graphic Design", "Adobe tutorials", "Behance"],
        careers: ["Graphic Designer", "Visual Designer", "Brand Designer", "Art Director", "Creative Director"],
        tools: ["Adobe Photoshop", "Illustrator", "Figma", "Canva", "InDesign"] },
      { id: "video-prod", title: "Video Production & Editing", description: "Create professional video content.",
        intro: "Video Production encompasses planning, filming, and editing video content for entertainment, marketing, education, and social media.",
        importance: "Video is the most engaging content format. From YouTube to corporate training, video skills are highly valuable.",
        skills: ["Cinematography", "Video Editing", "Color Grading", "Sound Design", "Motion Graphics", "Storytelling"],
        path: [{ level: "Beginner", steps: "Smartphone filming → Basic editing → YouTube content" }, { level: "Intermediate", steps: "Premiere Pro/DaVinci → Color grading → Sound design" }, { level: "Advanced", steps: "After Effects → Cinematography → Commercial production" }],
        howToLearn: "Start filming with your phone. Learn editing with free tools like DaVinci Resolve. Create YouTube videos for practice.",
        youtube: ["https://www.youtube.com/embed/O6ERELse_QY", "https://www.youtube.com/embed/Xz6yBbBRr8Y"],
        freePlatforms: ["DaVinci Resolve (free)", "YouTube Creator Academy", "Coursera – Content Creation", "Skillshare (free trial)"],
        careers: ["Video Editor", "Content Creator", "Videographer", "Motion Designer", "Film Director"],
        tools: ["DaVinci Resolve", "Premiere Pro", "After Effects", "Final Cut Pro", "OBS Studio"] },
      { id: "game-design", title: "Game Design & Development", description: "Create interactive gaming experiences.",
        intro: "Game Development combines programming, art, design, and storytelling to create interactive entertainment experiences.",
        importance: "Gaming is a massive industry surpassing film and music combined. It offers creative and lucrative career paths.",
        skills: ["Unity / Unreal Engine", "C# / C++", "Game Design", "3D Modeling", "Physics Simulation", "Level Design"],
        path: [{ level: "Beginner", steps: "Game design concepts → Unity + C# → 2D games" }, { level: "Intermediate", steps: "3D games → Physics → AI → Multiplayer basics" }, { level: "Advanced", steps: "Shaders → Performance → Publishing → Studio workflow" }],
        howToLearn: "Start with Unity and make a simple 2D platformer. Learn C# alongside. Join game jams for practice.",
        youtube: ["https://www.youtube.com/embed/XtQMytORBmM", "https://www.youtube.com/embed/pwmXYc5n5OC"],
        freePlatforms: ["Unity Learn", "Unreal Engine free", "CS50 Game Development", "Brackeys YouTube"],
        careers: ["Game Developer", "Game Designer", "Unity Developer", "Level Designer", "Technical Artist"],
        tools: ["Unity", "Unreal Engine", "Blender", "Godot", "Aseprite"] }
    ]
  },
  {
    id: "security",
    icon: "🛡️",
    title: "Security & Compliance",
    description: "Protect organizations from threats and ensure regulatory compliance.",
    subDomains: [
      { id: "ethical-hacking", title: "Ethical Hacking & Penetration Testing", description: "Find vulnerabilities before attackers do.",
        intro: "Ethical Hacking involves authorized attempts to gain unauthorized access to systems to discover security vulnerabilities.",
        importance: "Organizations pay ethical hackers to find and fix vulnerabilities before malicious hackers exploit them.",
        skills: ["Reconnaissance", "Vulnerability Scanning", "Exploitation", "Post-Exploitation", "Reporting", "OWASP"],
        path: [{ level: "Beginner", steps: "Networking → Linux → Basic security tools" }, { level: "Intermediate", steps: "Web app hacking → Network pentesting → Scripting" }, { level: "Advanced", steps: "Advanced exploitation → Red teaming → Bug bounties → CEH/OSCP" }],
        howToLearn: "Set up Kali Linux. Practice on TryHackMe and HackTheBox. Work toward OSCP certification.",
        youtube: ["https://www.youtube.com/embed/3Kq1MIfTWCE", "https://www.youtube.com/embed/fNzpcB7ODxQ"],
        freePlatforms: ["TryHackMe", "HackTheBox", "PortSwigger Web Security Academy", "OWASP WebGoat"],
        careers: ["Penetration Tester", "Security Consultant", "Bug Bounty Hunter", "Red Team Operator"],
        tools: ["Kali Linux", "Burp Suite", "Metasploit", "Nmap", "Wireshark"] },
      { id: "compliance", title: "IT Compliance & Governance", description: "Ensure organizations meet regulatory requirements.",
        intro: "IT Compliance ensures that organizations adhere to laws, regulations, and standards governing data protection and IT operations.",
        importance: "With regulations like GDPR and HIPAA, compliance professionals are essential to avoid legal penalties and protect user data.",
        skills: ["GDPR", "HIPAA", "ISO 27001", "SOC 2", "Risk Assessment", "Audit Management"],
        path: [{ level: "Beginner", steps: "IT governance concepts → Major regulations → Risk basics" }, { level: "Intermediate", steps: "ISO 27001 → Audit processes → Policy writing → Incident response" }, { level: "Advanced", steps: "Enterprise GRC → Multi-framework compliance → CISO advisory" }],
        howToLearn: "Study major frameworks (ISO 27001, SOC 2). Take ISACA or ISC2 intro courses. Understand GDPR thoroughly.",
        youtube: ["https://www.youtube.com/embed/yrOQ9wXsP2k", "https://www.youtube.com/embed/CivG_2UqKMg"],
        freePlatforms: ["ISACA free resources", "NIST Cybersecurity Framework", "Coursera – IT Security", "ICO (GDPR resources)"],
        careers: ["Compliance Analyst", "GRC Analyst", "IT Auditor", "Information Security Manager", "DPO"],
        tools: ["ServiceNow GRC", "OneTrust", "Qualys", "Nessus", "Archer"] }
    ]
  },
  {
    id: "career-support",
    icon: "🎯",
    title: "Career Support Domains",
    description: "Essential skills to land and grow in your dream tech career.",
    subDomains: [
      { id: "resume", title: "Resume Building & Personal Branding", description: "Stand out in the job market.",
        intro: "Resume building and personal branding help you present your skills, experience, and value proposition effectively to potential employers.",
        importance: "Your resume and online presence are your first impression. Strong personal branding can open doors to opportunities.",
        skills: ["Resume Writing", "LinkedIn Optimization", "Portfolio Building", "Cover Letters", "GitHub Profile", "Networking"],
        path: [{ level: "Beginner", steps: "Resume fundamentals → LinkedIn setup → GitHub profile" }, { level: "Intermediate", steps: "Portfolio website → Content creation → Networking strategy" }, { level: "Advanced", steps: "Thought leadership → Speaking engagements → Community building" }],
        howToLearn: "Use resume templates. Optimize your LinkedIn with keywords. Build a portfolio website showcasing projects.",
        youtube: ["https://www.youtube.com/embed/Tt08KmFfIYQ", "https://www.youtube.com/embed/u75hUSShvnc"],
        freePlatforms: ["LinkedIn Learning (free courses)", "Novoresume (free tier)", "GitHub Pages", "Dev.to"],
        careers: ["Any tech role – this is a meta-skill for career advancement"],
        tools: ["LinkedIn", "Novoresume", "GitHub", "Canva", "WordPress"] },
      { id: "interview-prep", title: "Technical Interview Preparation", description: "Crack coding interviews at top tech companies.",
        intro: "Technical interview preparation covers coding challenges, system design, and behavioral questions asked by top tech companies.",
        importance: "Structured preparation is the difference between getting hired and getting rejected. It's a learnable skill.",
        skills: ["Data Structures & Algorithms", "System Design", "Behavioral Questions", "Mock Interviews", "Time Management"],
        path: [{ level: "Beginner", steps: "DSA basics → Easy LeetCode → STAR method for behavioral" }, { level: "Intermediate", steps: "Medium LeetCode → System design intro → Mock interviews" }, { level: "Advanced", steps: "Hard LeetCode → Advanced system design → Negotiation skills" }],
        howToLearn: "Solve 2-3 LeetCode problems daily. Practice system design weekly. Do mock interviews with peers.",
        youtube: ["https://www.youtube.com/embed/1qw5ITr3k9E", "https://www.youtube.com/embed/ii9z_2bmFEE"],
        freePlatforms: ["LeetCode", "NeetCode.io", "Pramp (free mock interviews)", "InterviewBit"],
        careers: ["Software Engineer at FAANG", "Staff Engineer", "Engineering Manager"],
        tools: ["LeetCode", "NeetCode", "Pramp", "Excalidraw", "Notion"] },
      { id: "freelancing", title: "Freelancing & Remote Work", description: "Build a successful independent tech career.",
        intro: "Freelancing allows you to work independently, choose your projects, and build a flexible career in technology.",
        importance: "The gig economy is booming. Freelancing offers freedom, higher earning potential, and diverse project experience.",
        skills: ["Client Communication", "Proposal Writing", "Pricing Strategy", "Time Management", "Contract Negotiation", "Self-Marketing"],
        path: [{ level: "Beginner", steps: "Build skills → Create profiles → First small projects" }, { level: "Intermediate", steps: "Niche specialization → Portfolio → Client management → Pricing" }, { level: "Advanced", steps: "Agency building → Passive income → Consulting → Mentorship" }],
        howToLearn: "Build a strong portfolio. Start with small projects on Upwork or Fiverr. Deliver excellent work to build reputation.",
        youtube: ["https://www.youtube.com/embed/dSMnJfLB0aw", "https://www.youtube.com/embed/fZIhMTRiYo0"],
        freePlatforms: ["Upwork (free to join)", "Fiverr", "Toptal blog", "Freelancer.com"],
        careers: ["Freelance Developer", "Independent Consultant", "Agency Owner", "Digital Nomad"],
        tools: ["Upwork", "Fiverr", "Notion", "Toggl", "Stripe/PayPal"] }
    ]
  }
];
